version: '2.1'
#creating container for redis
services:  
 redis_image:
  image: redis
  container_name: cachev1  
  ports:
   - "6379:6380" 
#creating container for web api(backend)
 web:              
  build:
   context: .
   dockerfile: ./Backend/WeatherAPIDotNetCore/Dockerfile
#setting up environment variables
  environment:
   - CosmosConnectionString=$CosmosConnectionString
   - CosmosDatabaseName=$CosmosDatabaseName
   - RedisConnectionString=redis_image
   - WeatherCollectionName=$WeatherCollectionName
   - MapsAPIKey=$MapsAPIKey   
  links:
   - redis_image
  container_name: DotNetCore-Service  
  restart: always  
  ports:
   - "5000:80"       
  depends_on:
   - redis_image
#creating container for angular(frontend)
 weatherapp:              
  build:
   context: .
   dockerfile: ./Frontend/Dockerfile
  links:
   - redis_image
   - web
  container_name: weatherApp
  restart: always
  ports:
   - "81:80"       
  depends_on:
   - redis_image
   - web
